services:
  fastapi:
    build: .
    volumes:
      - ollama-model:/root/.ollama
    image: chasea1135/pari_lab_server:latest
    ports:
      - "5000:5000"
    environment:
      - OLLAMA_MODEL_PATH=/root/.ollama

volumes:
  ollama-model:
