services:
  fastapi:
    build: .
    volumes:
      - ollama-model:/root/.ollama
    image: chasea1135/pari_lab_server:latest
    ports:
      - "${SERVER_PORT:-5000}:${SERVER_PORT:-5000}"
    environment:
      - OLLAMA_HOST=0.0.0.0:11434
      - SERVER_HOST=${SERVER_HOST}
      - SERVER_PORT=${SERVER_PORT}
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  ollama-model:
