name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Trigger action on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME_USER1 }}
          password: ${{ secrets.DOCKER_PASSWORD_USER1 }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: chasea1135/pari_lab_server:latest
